### ISSUE TITLE
Depends on CC Tweaked, CC Modded is an alternative

### ISSUE THREAD

**Issue by BraveCaperCat2** [TechTastic/CC-Shops#2]
In CurseForge the mod depends on CC Tweaked. this will also likely be true in Minecraft as well. please add CC Modded as an alternative to CC Tweaked so it can be used too.

**Comment by TechTastic** [comment]
Did you try running it with CC Modded?

**Comment by TechTastic** [comment]
Ok, so i just tried it with CC: Modded, it seems they got rid of an essential method i was using throughout and upon further talks with other CC developers, I have decided not to support CC: Modded

**Comment by BraveCaperCat2** [comment]
ok I will go talk about re-adding it over at CC: Modded.
